rapid7/metasploit_data_models

app/models/mdm/service.rb, db/migrate/20150112203945_remove_duplicate_services.rb, lib/metasploit_data_models/version.rb, spec/app/models/mdm/service_spec.rb, spec/dummy/db/structure.sql
Adds a Uniqueness validation on Service, so a Host can only have on Service with the same port and proto
Complete these steps on DESTINATION
If the change are compatible with the previous branch's API, then increment [`PATCH`](lib/metasploit_data_models/version.rb).
If your changes are incompatible with the previous branch's API, then increment
[`MINOR`](lib/metasploit_data_models/version.rb) and reset [`PATCH`](lib/metasploit_data_models/version.rb) to `0`.
[`MINOR`](lib/metasploit_data_models/version.rb) and [`PATCH`](lib/metasploit_data_models/version.rb) and commit the changes.
=> Bug/msp 11643/service uniqueness2

app/models/mdm/service.rb, lib/metasploit_data_models/version.rb
MSP-11643
We now verify the combination of port and protocol within the scope of the parent host ID, versus verifying host_id is unique within the scope of port/proto. This allows the validation messages to have somewhere to appear in the service add window, associated with the port and protocol fields.
=> MSP-11643: Correction to service uniqueness on host validation

app/models/mdm/service.rb, lib/metasploit_data_models/version.rb
Reverts rapid7/metasploit_data_models#91, due to unforeseen issues with the fix.
Follow the post-release steps in #91.
=> Revert "MSP-11643: Correction to service uniqueness on host validation"

db/migrate/20110317144932_add_session_table.rb, db/migrate/20110513143900_track_successful_exploits.rb, lib/metasploit_data_models/version.rb
This PR updates the #find_all_by_X to rails 4 #where syntax.
For example:
Old syntax: `services.find_all_by_host_id(host_id).each do |e|`
New syntax: `services.where(host_id: host_id).each do |e|`
=> MSP-12014: Convert find_all_by_X to Rails 4 compatible syntax

db/migrate/20100819123300_migrate_cred_data.rb, db/migrate/20110422000000_convert_binary.rb, db/migrate/20110513143900_track_successful_exploits.rb, db/migrate/20110517160800_rename_and_prune_nessus_vulns.rb, db/migrate/20111011110000_add_display_name_to_reports_table.rb, lib/metasploit_data_models/version.rb
This PR updates the #find(:all) to rails 4 #where or #all syntax.
For example:
Old syntax: `Mdm::Note.find(:all).each do |note|`
New syntax: `Mdm::Note.all.each do |note|`
Old syntax: `Mdm::Task.find(:all, :conditions => { :completed_at => nil }).each do |t|`
New syntax: `Mdm::Task.where(completed_at: `nil).each do |t|`
Old syntax: `all_hosts = myworkspace.hosts.find(:all)`
New syntax: `all_hosts = myworkspace.hosts`
=> MSP-12011: Convert find(:all) to Rails 4 compatible

app/models/mdm/workspace.rb, lib/metasploit_data_models/version.rb
This PR updates the #find_or_create_by to rails 4 #where().first_or_create syntax.
For example:
Old syntax: `Apps::AppCategory.find_or_create_by_name!(cat)`
New syntax: `Apps::AppCategory.where(name: cat).first_or_create!`
Old syntax: `workspace = Mdm::Workspace.find_or_create_by_name(WORKSPACE, owner_id: user.id)`
New syntax: `workspace = Mdm::Workspace.where(name: WORKSPACE).first_or_create(owner_id: user.id)`
=> MSP-12016: Convert find_or_create_by to Rails 4 compatible

.travis.yml, Rakefile, lib/metasploit_data_models/version.rb
MSP-11929
Turn on containerized builds using `sudo: false` for faster build startup.  Turn on bundle caching with `cache: bundler` for faster build install.  Replace `jruby-19mode` with `jruby-1.7.17` to work around https://github.com/travis-ci/travis-ci/issues/3067 and https://github.com/wayneeseguin/rvm/issues/3242, which is unrelated to this chore, but a currently problem with travis-ci's rvm install and so would block any builds.  Fix bundler requires in `Rakefile` to make it work when the bundle is uncached.  `bundle exec rake db:setup` instead of just `rake db:setup` for bundler cache compatibility.  Remove rbx-2.2 to speed up overall build time as the rbx-2.2 build never succeeds and so just eats up job slots.  Clean up quoting in .travis.yml for compatibility with travis lint. …
=> Containerized build and other build improvements

Gemfile, lib/metasploit_data_models/version.rb, metasploit_data_models.gemspec
MSP-11141
Test that metasploit-model with metasploit-cache extracted, although it has an incompatible semantic version produces a compatible metasploit_data_models because nothing in metasploit_data_models depends on the code extracted to metasploit-cache.
- Incremented [`PATCH`](lib/metasploit_data_models/version.rb).
=> Use metasploit-model with metasploit-cache extracted

app/models/mdm/service.rb, db/migrate/20150212214222_remove_duplicate_services2.rb, lib/metasploit_data_models/version.rb, spec/app/models/mdm/service_spec.rb, spec/dummy/db/structure.sql
adds validation that you cannot have more than one service on a host with the same port and protocol
Complete these steps on DESTINATION
If the change are compatible with the previous branch's API, then increment [`PATCH`](lib/metasploit_data_models/version.rb).
If your changes are incompatible with the previous branch's API, then increment
[`MINOR`](lib/metasploit_data_models/version.rb) and reset [`PATCH`](lib/metasploit_data_models/version.rb) to `0`.
[`MINOR`](lib/metasploit_data_models/version.rb) and [`PATCH`](lib/metasploit_data_models/version.rb) and commit the changes.
=> Bug/msp 11643/unique services

app/models/mdm/note.rb, app/models/mdm/vuln.rb, db/migrate/20150209195939_add_vuln_id_to_note.rb, lib/metasploit_data_models/version.rb, spec/app/models/mdm/note_spec.rb, spec/app/models/mdm/vuln_spec.rb, spec/dummy/db/structure.sql
=> Feature/msp 11994/add note id to vuln

app/models/metasploit_data_models/automatic_exploitation.rb, app/models/metasploit_data_models/automatic_exploitation/match.rb, db/migrate/20131002004641_create_automatic_exploitation_matches.rb, db/migrate/20131011184338_module_detail_on_automatic_exploitation_match.rb, db/migrate/20131021185657_make_match_polymorphic.rb, lib/metasploit_data_models/version.rb, spec/dummy/db/structure.sql
( land this if the [corresponding Pro PR](https://github.com/rapid7/pro/pull/1838) passes )
=> Feature/msp 11926/move auto exploitation match

app/models/metasploit_data_models/automatic_exploitation/match_result.rb, db/migrate/20131017150735_create_automatic_exploitation_match_results.rb, lib/metasploit_data_models/version.rb, spec/app/models/metasploit_data_models/automatic_exploitation/match_result_spec.rb, spec/app/models/metasploit_data_models/automatic_exploitation/match_spec.rb, spec/dummy/db/structure.sql
( land this if the corresponding Pro PR passes )
=> MSP-12143: Move auto exploitation MatchResult

app/models/metasploit_data_models/automatic_exploitation/match_result.rb, app/models/metasploit_data_models/automatic_exploitation/match_set.rb, app/models/metasploit_data_models/automatic_exploitation/run.rb, db/migrate/20131002164449_create_automatic_exploitation_match_sets.rb, db/migrate/20131008213344_create_automatic_exploitation_runs.rb, lib/metasploit_data_models/version.rb, spec/dummy/db/structure.sql
__note: it became obvious in doing this that MatchSet would need to be moved as well, so that is included in this PR__
=> Feature/msp 12172/move auto exploitation run

db/migrate/20150317145455_rename_module_indices.rb, lib/metasploit_data_models/version.rb, spec/dummy/db/structure.sql
Rename some index names that are causing build failures for rails 4 framework upgrade on Travis.
=> MSP-12307: Rename indices to match for rails 4

lib/metasploit_data_models/version.rb, metasploit_data_models.gemspec
MSP-12550
Update to use metasploit-concern 0.4.0
If the change are compatible with the previous branch's API, then increment [`PATCH`](lib/metasploit_data_models/version.rb).
If your changes are incompatible with the previous branch's API, then increment
[`MINOR`](lib/metasploit_data_models/version.rb) and reset [`PATCH`](lib/metasploit_data_models/version.rb) to `0`.
[`MINOR`](lib/metasploit_data_models/version.rb) and [`PATCH`](lib/metasploit_data_models/version.rb) and commit the changes.
=> Update to metasploit-concern 0.4.0

db/migrate/20150421211719_rename_automatic_exploitation_index.rb, lib/metasploit_data_models/version.rb, spec/dummy/db/structure.sql
MSP-12593
* Fixes structure.sql diffs
* Used to be ref_id but new naming convention for AE is module_detail_id
First run migrations on master. In mdm:
Then checkout staging/rails-4.0 and continue new migrations:
Perform these steps prior to pushing to DESTINATION or the build will be broke on DESTINATION.
=> Create migration to rename an AE match index

lib/metasploit_data_models/version.rb, spec/factories/mdm/module/details.rb
MSP-12678
- Incremented [`PATCH`](lib/metasploit_data_models/version.rb).
=> Fix factory_girl deprecation warning by converting ignore to transient

metasploit_data_models.gemspec
MSP-12669
- Incremented [`PATCH`](lib/metasploit_data_models/version.rb).
=> Upgrade to rspec-3.1

CONTRIBUTING.md, app/models/mdm/wmap_request.rb, app/models/mdm/wmap_target.rb, lib/metasploit_data_models/version.rb
MSP-12704
Fix merge error to fix undocumented object warnings from YARD that lead to build failure when YARD coverage was below 100%.
=> Fix build failures due to undocumented objects

app/models/mdm/vuln.rb, db/migrate/20150514182921_add_origin_to_mdm_vuln.rb, lib/metasploit_data_models/version.rb, spec/app/models/mdm/vuln_spec.rb, spec/dummy/db/structure.sql
MSP-12395
Add polymorphic relationship between `Mdm::Vuln` and it's origin
--
--
**Database Columns**
**Polymorphic Association**
--
--
- Incremented `MINOR`, and reset `PATCH` to 0
=> Polymorphic relationship between Mdm::Vuln and it's origin

lib/metasploit_data_models/version.rb, metasploit_data_models.gemspec
MSP-12735
Closes #125
Recog has been bumped to version 2.0 for future updates. As a result, metasploit_data_models and metasploit-framework needs to be bumped as well. 
=> Updates recog to 2.0, bumps version to 1.2.0

app/models/metasploit_data_models/automatic_exploitation/match_result.rb, lib/metasploit_data_models/version.rb
=> MSP-12741: Adds by_workspace scopes back to MatchResult

app/models/mdm/module/detail.rb, lib/metasploit_data_models/version.rb, spec/app/models/metasploit_data_models/automatic_exploitation/match_spec.rb, spec/factories/metasploit_data_models/automatic_exploitation/matches.rb
=> Ensure Match objects persist after Detail delete

app/models/mdm/tag.rb, config/locales/en.yml, lib/metasploit_data_models/version.rb, spec/app/models/mdm/tag_spec.rb
=> Bug/msp 10957/tag char validation

app/models/mdm/web_page.rb, lib/metasploit_data_models/version.rb
MSP-12834
rapid7/metasploit-framework#5515
=> Bug/msp 12834/crawler choke on save

lib/mdm/host/operating_system_normalization.rb, lib/metasploit_data_models/version.rb, spec/app/models/mdm/host_spec.rb, spec/app/models/mdm/service_spec.rb
Fixes #132.
Due to an improper use of Hash.merge in https://github.com/rapid7/metasploit_data_models/blob/10fce8e90f20688ef78de054d54c4031425662a4/lib/mdm/host/operating_system_normalization.rb#L207-228, no fingerprints that would normally be matched and returned from recog will ever be returned.  
It is understood that all of this is a little kludgy right now and is probably a good candidate for refactoring, especially given the intent in https://github.com/rapid7/metasploit-framework/pull/5563, but for now I'm looking to simply get this functionality fixed and we can ponder a larger refactor later.
=> Properly match Recog service information

Gemfile, lib/metasploit_data_models/version.rb, spec/app/models/mdm/module/detail_spec.rb, spec/app/models/mdm/service_spec.rb, spec/app/models/mdm/web_vuln_spec.rb, spec/app/models/mdm/workspace_spec.rb, spec/app/models/metasploit_data_models/ip_address/v4/segment/single_spec.rb, spec/app/models/metasploit_data_models/search/operator/multitext_spec.rb, spec/lib/metasploit_data_models/ip_address/cidr_spec.rb, spec/spec_helper.rb
MSP-12396
* Enhancements
* Update to shoulda-matchers 3.0.0
This is a changed to the test dependencies **only**.  There is no need to release it to rubygems.org.
=> Update to shoulda-matchers 3.0.0

app/models/mdm/vuln.rb, lib/metasploit_data_models/version.rb, spec/app/models/mdm/vuln_spec.rb
MS-120
* host name search scope added to vulns
=> Add search on vulns tables by host name column

app/models/mdm/host.rb, lib/metasploit_data_models/version.rb, spec/app/models/mdm/host_spec.rb
Often, it is convenient to allow localhost to be a valid host IP; for instance when testing, or when using a proxy or tunnel configuration. Our current localhost exclusion does not actually prevent all local IPs from being included as a host element anyway (e.g. ipv6 is not excluded, all of the other 127.0.0/8 addresses, etc.) so the current exclusion of 127.0.0.1 does not provide a lot of value, at least from metasploit-framework's point-of-view.
Complete these steps on DESTINATION
* "Enhancements" are widdening the API, such as by adding new classes or methods.
* "Bug Fixes" are fixes to the implementation that do not affect the public API.  If the public API is affected then
the change should be listed as both a "Bug Fix" and either an "Enhancement" or "Incompatible Change" depending …
=> remove exclusion of localhost address 127.0.0.1

app/models/mdm/host.rb, lib/metasploit_data_models/version.rb
Use an actual scope to uniq the relation for module details, instead of uniq: true
MS-1082
VERIFICATION STEPS
=> fix uniq scope on host

app/models/mdm/host.rb, lib/metasploit_data_models/version.rb
Fixes the deprecation warning about using a hash in a model scope
Replaced the hash with a splatted where
=> Bug/ms 896/hash scope

app/models/metasploit_data_models/search/visitor/relation.rb, lib/metasploit_data_models/version.rb, spec/app/models/metasploit_data_models/search/visitor/relation_spec.rb
Perform these steps prior to pushing to DESTINATION or the build will be broke on DESTINATION.
=> MS-895: Fix Model.scoped deprecation

app/models/mdm/host.rb, app/models/mdm/vuln.rb, lib/metasploit_data_models/version.rb
MS-899
DEPRECATION WARNING: It looks like you are eager loading table(s) that are referenced in a string SQL snippet.
Perform these steps prior to pushing to rails-4-deprecations or the build will be broke on rails-4-deprecations.
```
PRERELEASE = "rails-4.0-dev"
```
=> Bug/ms 899/string sql eager load

app/models/mdm/web_page.rb, lib/metasploit_data_models.rb, lib/metasploit_data_models/version.rb, spec/app/models/mdm/web_page_spec.rb
Adds WEBrick standard library to Mdm::WebPage so that cookie attribute can support WEBrick::Cookie objects on serialization. It fixes an issue in encountered in Pro.
MSP-13193
* Enhancements
* `Mdm::WebPage#cookie` can support `WEBrick::Cookie` objects on serialization
```
cookie = WEBrick::Cookie.new('test name', 'test value')
wp = Mdm::WebPage.create(cookie: cookie, web_site_id: 1, code: 'doge')
wp.cookie
```
- Incremented [`PATCH`](lib/metasploit_data_models/version.rb). (Should be 1.2.8)
=> Cookie attribute can support WEBrick::Cookie objects on serialization

app/models/mdm/workspace.rb
the unique web forms method was expecting an implicit
to_a on a relation before calling #reject! change this
to an explicit to_a to fix the error
MS-1235
VERIFICATION STEPS
=> explitly call to_a on relation

app/models/mdm/workspace.rb, spec/app/models/mdm/workspace_spec.rb, spec/spec_helper.rb
The validation is moved to framework, where it can be tested properly.
MS-902
Verification
========
=> Remove workspace IP validation

Gemfile, metasploit_data_models.gemspec
unlock all the gem versions that we can
for rails 4.1 support
MS-1330
VERIFICATION STEPS
=> update gem dependencies

lib/mdm/host/operating_system_normalization.rb
This change allows metasploit data models to accept Unicode data and allows it to pass the data to the database correctly.  Specifically, this change prevents  the Unicode domain and hostname data to be fed into an ANSI matching function that attempts to determine computer use.  Primarily, this determination is made from attempting to match on the the operating system name and type, so loss of the hostname and domain data should not affect the purpose determination.  
Testing requires access to domain-joined targets is listed in the dependent metasploit framework, and should be done in conjunction with the associated framework PR.
=> Update MDM to allow passthough for Unicode domain names

.travis.yml, config/initializers/ipaddr.rb, spec/dummy/db/structure.sql
```
IPAddr.new('10.0.0.1') == 'foo'
(irb):1: warning: Comparable#== will no more rescue exceptions of #<=> in the next release.
(irb):1: warning: Return nil in #<=> if the comparison is inappropriate or avoid such comparison.
```
```
IPAddr.new('10.0.0.1') == 'foo'
```
=> Update ipaddr monkeypatch

app/models/mdm/service.rb, spec/app/models/mdm/service_spec.rb
This fix ensures a valid port number is provided when a user creates a service on a host.  This was logged against Metasploit Pro and can be verified against Metasploit Pro.
See MS-2216.
-----
=> Ensure valid port settings when adding a service to a host.

app/models/mdm/host.rb, app/models/mdm/workspace.rb, spec/dummy/db/structure.sql
when a workspace has a lot of session events and events it can take a LONG time to delete
instead of instanciating each object and calling destroy I'm switching it over to delete_all
which happens in the database. this is a valid stratagy because these two models dont have any
hooks around deletion and they dont have any has_many relationships (so no orphaned grand children)
=> Speeds up workspace deletion

spec/factories/mdm/creds.rb, spec/factories/mdm/nexpose_consoles.rb, spec/factories/mdm/services.rb, spec/factories/mdm/users.rb, spec/factories/metasploit_data_models/automatic_exploitation/match_results.rb, spec/factories/module_runs.rb
Followed these instructions:
```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:
active { true }
To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:
rubocop \
--require rubocop-rspec \
--only FactoryBot/AttributeDefinedStatically \
--auto-correct
```
=> update tests for latest version of factory-bot

lib/mdm/host/operating_system_normalization.rb
This is in support of https://github.com/rapid7/recog/pull/218, which will fix https://github.com/rapid7/recog/issues/61 and significantly improves fingerprinting of UPnP endpoints.
I could use assistance in getting this tested and landed.
=> Update recog fingerprinting in support of unifying UPnP and HTTP fingerprinting

lib/mdm/host/operating_system_normalization.rb
Untested.  I suspect the contributing steps have changed but the documentation hasn't.
Required for https://github.com/rapid7/metasploit-framework/pull/8452
=> Utilize SMB native LM results for fingerprinting, if available

README.md, lib/metasploit_data_models/version.rb
This should fix the automated gem building for this gem by forcing a rebuild with a version bump, followed by a non-version bump. Currently the state machine is out of sync for bumping versions, which is causing problems with automation.
=> Fix version bumping

Gemfile
Factory bot updates in the 5.x stream fail test.  Lock for now.
=> restrict factory_bot to 4.x for now

app/models/mdm/async_callback.rb, app/models/mdm/workspace.rb, db/migrate/20180308134512_create_async_callbacks.rb, db/migrate/20190308134512_create_async_callbacks.rb, lib/mdm.rb
---
This PR adds a new Mdm model for asynchronous payloads.  It will track incoming connections for UUID-based pingback payloads, collecting the listener which received the connection and the originating IP address and port of the connection.
Note that a future PR will likely track outgoing taskings and returned data from asynchronous payloads, but that's outside the scope of this work.
To link your `metasploit-framework` to this pull request, use one of the following two methods:
- **Link directly to Github:** In your `metasploit-framework` repo, edit the Gemfile and add this line to the `:development` group: `gem 'metasploit_data_models', :git => 'git@github.com:rapid7/metasploit_data_models.git', :branch => 'add_async_callback_model'`
- **Link to a local copy of the …
=> Add async_callback tables and migrations

app/models/mdm/payload.rb, app/models/mdm/workspace.rb, db/migrate/20190507120211_remove_payload_workspaces.rb
This PR, by suggestion of @bcook-r7 (AKA @busterb), removes references to `workspace` from our recent `Payload` model (#172).  When a host calls back, the `host` is part of a workspace, but the `payload` shouldn't be.
Unknown questions:
- Does this break any other functionality (for example, in Metasploit Pro)?  Hopefully not, since the `payload` PR was only landed a month ago.
- What am I missing?
To link your `metasploit-framework` to this pull request, use one of the following two methods:
- **Link directly to Github:** In your `metasploit-framework` repo, edit the Gemfile and add this line to the `:development` group: `gem 'metasploit_data_models', :git => 'git@github.com:rapid7/metasploit_data_models.git', :branch => 'add_async_callback_model'`
- **Link to a local copy of the …
=> Remove reference to 'workspace' from the 'payloads' table

app/models/mdm/api_key.rb, app/validators/ip_format_validator.rb, app/validators/parameters_validator.rb
While evaluating code in metasploit for Rails 5 I missed that error syntax for the models changed.
Update convert direct assignment to call to `.add` [errors](https://api.rubyonrails.org/classes/ActiveModel/Errors.html).
=> update error messages for rails 5

app/models/mdm/note.rb, spec/app/models/mdm/host_spec.rb
https://www.levups.com/en/blog/2017/undocumented-dirty-attributes-activerecord-changes-rails51.html
Updated syntax for callback check, this can be demonstrated by obtaining a valid session with Framework.  Once the session complete it reports a note as an `os.fingerprint` that populates hostname and some attained OS details.
=> migrate to rails 5 syntax for note callback status

app/models/mdm/workspace.rb
* Mdm::Cred association in the workspace object were being defined as going through object that need to be defined earlier
=> Workspace association changes

app/models/metasploit_data_models/search/visitor/where.rb, metasploit_data_models.gemspec, spec/app/models/metasploit_data_models/search/visitor/where_spec.rb
* migrate from `in` to `between` per warning for Rails 6 deprecation
* set min ruby 2.4
=> remove deprecation warnings

db/migrate/20190308134512_create_async_callbacks.rb, spec/app/models/metasploit_data_models/ip_address/v4/segment/single_spec.rb
The constraint on `:uuid` is in the column define already
This was noted while doing some exploratory testing for Rails 6 migration support.
=> remove duplicate contraint

Gemfile, README.md, app/models/metasploit_data_models/ip_address/v4/segment/nmap/list.rb, app/models/metasploit_data_models/search/visitor/relation.rb, config/initializers/arel_helper.rb, lib/metasploit_data_models/version.rb, metasploit_data_models.gemspec, spec/app/models/metasploit_data_models/search/visitor/attribute_spec.rb, spec/dummy/app/models/application_record.rb, spec/dummy/config/application.rb, spec/dummy/config/storage.yml, spec/dummy/db/structure.sql
Allow usage with Rails 6.x
Documents the `ArelHelper` classes that must be included in `ApplicationRecord` for any project will utilize the models in this Rails Engine.
Depends on https://github.com/rapid7/metasploit-model/pull/57 & https://github.com/rapid7/metasploit-concern/pull/33 land and release.
=> update to Rails 6.x compatible

.github/workflows/verify.yml, db/migrate/20140905031549_add_detected_arch_to_host.rb, spec/app/models/metasploit_data_models/search/operation/range_spec.rb
Adding test coverage for Ruby 3.0
Also pinning the bundler version to 2.1.4 until this issue rubygems/rubygems#4539 has been addressed
=> Add ruby 3.0 to CI

app/models/mdm/listener.rb, spec/app/models/mdm/listener_spec.rb
Not all handlers (listeners) will have a task at all times.
=> listener does not always have a task

.github/workflows/verify.yml, Gemfile, Rakefile
This PR updates the Github Workflow to use Ubuntu 18.04 rather than the deprecated 16.04.
It also uses the updated ruby setup tool [ruby/setup-ruby@v1](https://github.com/ruby/setup-ruby) instead of the older [actions/setup-ruby@v1](https://github.com/actions/setup-ruby).
It also fixes the current CI warning:
> Lint : .github#L1The ubuntu-16.04 environment is deprecated and will be removed on September 20, 2021. Migrate to ubuntu-latest instead. For more details see https://github.com/actions/virtual-environments/issues/3287
=> Update Ubuntu version & Ruby Setup action

Gemfile, app/models/mdm/host_tag.rb, app/models/mdm/tag.rb, app/models/mdm/workspace.rb, lib/metasploit_data_models/engine.rb, lib/metasploit_data_models/version.rb, metasploit_data_models.gemspec, spec/dummy/config/application.rb, spec/dummy/config/environments/development.rb, spec/dummy/config/environments/production.rb, spec/dummy/config/initializers/assets.rb
Updates to support Rails 7
* adjusts a caching issue around an `after_destroy` call that can cause failure to remove an orphaned tag.
* Fixes an typo is a `Workspace` relationship
* Remove configuration references to `assets` not used in the gem
* Updates test `ActiveRecord` connection handling to remove testing warning.
=> Add support for rails 7

app/models/mdm/loot.rb, spec/app/models/mdm/loot_spec.rb
Rails 7 validation expands on `belongs_to` validation change from #193
* loot is not require to associated directly to a host
* loot must attach attach to a workspace
=> relax loot model to remove host requirement

Gemfile, app/models/mdm/event.rb, app/models/mdm/listener.rb, app/models/mdm/loot.rb, app/models/mdm/macro.rb, app/models/mdm/nexpose_console.rb, app/models/mdm/note.rb, app/models/mdm/profile.rb, app/models/mdm/session.rb, app/models/mdm/task.rb, app/models/mdm/user.rb, app/models/mdm/web_form.rb, app/models/mdm/web_page.rb, app/models/mdm/web_site.rb, app/models/mdm/web_vuln.rb, spec/dummy/config/application.rb
`metasploit_data_models` does not have a `Gemfile.lock` so a fresh checkout will install Rails 7.2 - which breaks this repository. This pull request updates the repository to work with Rails 7.2
=> Fix rails 7.2 errors and warnings

app/models/mdm/event.rb, app/models/mdm/listener.rb, app/models/mdm/loot.rb, app/models/mdm/macro.rb, app/models/mdm/nexpose_console.rb, app/models/mdm/note.rb, app/models/mdm/profile.rb, app/models/mdm/session.rb, app/models/mdm/task.rb, app/models/mdm/user.rb, app/models/mdm/web_form.rb, app/models/mdm/web_page.rb, app/models/mdm/web_site.rb, app/models/mdm/web_vuln.rb
Continuation of https://github.com/rapid7/metasploit_data_models/pull/204 which added Rails 7.1 support - but it was never released to rubygems
Updates this repo to align with the convention used in https://github.com/rapid7/metasploit-credential/pull/180
=> Update Rails 7.1 support

app/models/mdm/event.rb, app/models/mdm/listener.rb, app/models/mdm/session.rb, app/models/mdm/task.rb, app/models/mdm/web_vuln.rb, lib/metasploit_data_models/base64_serializer.rb
This PR changes the handling of the data that is being passed to the `dump` method.
This aims to fix an issue where `nil` would be forcefully coerced to an empty string, breaking code that would rely on nil values in Pro.
- Point Pro & Framework at this branch
- Run the session tests in Pro
- Passing CI
=> Add coerce param to Base64Serializer

Gemfile, app/models/mdm/payload.rb, db/migrate/20110317144932_add_session_table.rb, db/migrate/20110422000000_convert_binary.rb, spec/app/models/mdm/payload_spec.rb, spec/dummy/config/application.rb, spec/factories/mdm/payloads.rb
We need to specify a coder here to be compatible with Rails 7.1
Tested as part of the framework PR rails 7.1 here: https://github.com/rapid7/metasploit-framework/pull/19953
Rails 7.0 here: https://github.com/rapid7/metasploit-framework/pull/19977
=> Specify YAML coder for mdm payload

lib/metasploit_data_models/version.rb
Manual version bump as automatic one failed last time
version 6.0.6 already exists in rubygems https://rubygems.org/gems/metasploit_data_models/versions/6.0.6
=> Manual version bump as automatic one failed last time

.github/workflows/verify.yml
This PR updates the [verify.yml](https://github.com/rapid7/metasploit_data_models/compare/master...cgranleese-r7:metasploit_data_models:update-workflow-to-run-against-rails-versions?expand=1#diff-b32b798d8ec577b859922a84b90dfe871b19fad404cc6fa7a6fe163f079fbcbf) workflow to now be tested against a matrix of Rails versions.
=> Updates workflow to run against rails versions

.github/workflows/verify.yml
Version 20.04 is being dropped from Github's official support:
> This is a scheduled Ubuntu 20.04 brownout. Ubuntu 20.04 LTS runner will be removed on 2025-04-15. For more details, see https://github.com/actions/runner-images/issues/11101
The tests were failling on: https://github.com/rapid7/metasploit_data_models/pull/208 which prompted this fix.
=> Bump ubuntu version in verify.yml

.github/workflows/verify.yml, metasploit_data_models.gemspec
This updates this workflow to make use off the shared pipeline added as part of https://github.com/rapid7/metasploit-framework/pull/20001.
Initially this PR will point at these new pipelines on my @cgranleese-r7 repository for testing. Once this is landed, I will rebase this PR.
Related PRs:
- https://github.com/rapid7/metasploit-framework/pull/20001
- https://github.com/rapid7/metasploit-concern/pull/45
- https://github.com/rapid7/metasploit-credential/pull/189
- https://github.com/rapid7/metasploit-model/pull/73
- https://github.com/rapid7/metasploit_data_models/pull/216
- https://github.com/rapid7/rex-core/pull/43
- https://github.com/rapid7/rex-exploitation/pull/46/
- https://github.com/rapid7/rex-mime/pull/9
- https://github.com/rapid7/rex-powershell/pull/45
- …
=> Updates verify workflow to use shared pipeline
